import type { Category } from "./types";

export const categories: Category[] = [
  {
    slug: "life",
    name: "생활",
    nameEn: "Daily life",
    description: "첫 7일, 전화, 학교, ESL, 혜택, 응급, 주소·교통, 커뮤니티",
    accent: "#2F6B4F",
    icon: "life",
  },
  {
    slug: "dmv",
    name: "DMV",
    nameEn: "Driver & Vehicle",
    description: "면허, 보험, 주별 가이드",
    accent: "#1B4F9C",
    icon: "car",
  },
  {
    slug: "bank",
    name: "은행",
    nameEn: "Banking",
    description: "계좌, 첫 신용카드, 신용점수, 송금",
    accent: "#0F6B5C",
    icon: "bank",
  },
  {
    slug: "medical",
    name: "의료",
    nameEn: "Healthcare",
    description: "보험, 저소득·메디케어, 병원, 응급 비용",
    accent: "#C23B3B",
    icon: "medical",
  },
  {
    slug: "tax",
    name: "세금",
    nameEn: "Taxes",
    description: "세금 신고, 예상세, 주세, SSN·ITIN",
    accent: "#8A5A12",
    icon: "tax",
  },
  {
    slug: "immigration",
    name: "이민국",
    nameEn: "USCIS",
    description: "계정·케이스, EAD, 가족·취업 이민, 학생·OPT, 귀화",
    accent: "#5C4A2E",
    icon: "immigration",
  },
  {
    slug: "job",
    name: "취업",
    nameEn: "Jobs",
    description: "현장 취업, 홈케어·돌봄, 스몰 비즈니스, 이력서",
    accent: "#3D3A8C",
    icon: "job",
  },
  {
    slug: "housing",
    name: "주거",
    nameEn: "Housing",
    description: "임대, 리스·룸메이트, 시니어 주거, 유틸리티, 보증금",
    accent: "#1F6F8B",
    icon: "housing",
  },
];
