import type { Category } from "./types";

export const categories: Category[] = [
  {
    slug: "life",
    name: "생활",
    nameEn: "Daily life",
    description: "첫 7일, 전화, 학교, 한국 서류, 혜택, 응급, 교통",
    accent: "#2F6B4F",
    icon: "life",
  },
  {
    slug: "dmv",
    name: "DMV",
    nameEn: "Driver & Vehicle",
    description: "면허, 보험, 사고·티켓·DUI, 주 ID, 렌트·차 구입",
    accent: "#1B4F9C",
    icon: "car",
  },
  {
    slug: "bank",
    name: "은행",
    nameEn: "Banking",
    description: "계좌, 첫 신용카드, 신용점수, 송금",
    accent: "#0F6B5C",
    icon: "bank",
  },
  {
    slug: "medical",
    name: "의료",
    nameEn: "Healthcare",
    description: "보험, 저소득·메디케어, 정신건강·약국, 병원",
    accent: "#C23B3B",
    icon: "medical",
  },
  {
    slug: "tax",
    name: "세금",
    nameEn: "Taxes",
    description: "세금 신고, 예상세, 주세, FBAR·해외금융, SSN·ITIN",
    accent: "#8A5A12",
    icon: "tax",
  },
  {
    slug: "immigration",
    name: "이민국",
    nameEn: "USCIS",
    description: "계정·케이스, 직장 비자, I-94·여행, EAD, 영주권·OPT",
    accent: "#5C4A2E",
    icon: "immigration",
  },
  {
    slug: "job",
    name: "취업",
    nameEn: "Jobs",
    description: "구직, 임금·산재, 실업급여, 홈케어, 이력서",
    accent: "#3D3A8C",
    icon: "job",
  },
  {
    slug: "housing",
    name: "주거",
    nameEn: "Housing",
    description: "임대·구매, 퇴거 분쟁, 리스·보험, 시니어",
    accent: "#1F6F8B",
    icon: "housing",
  },
];
